export { HeroSection } from '#/components/sections/hero/HeroSection'
export { StatsSection } from '#/components/sections/stats/StatsSection'
export { HomeEventsSection } from '#/components/sections/events/HomeEventsSection'
export { HomeCtaSection } from '#/components/sections/home/HomeCtaSection'
export { ProgramsSection } from '#/components/sections/programs/ProgramsSection'
