/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HackdscRouteRouteImport } from './routes/hackdsc/route'
import { Route as EventsRouteRouteImport } from './routes/events/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HackdscIndexRouteImport } from './routes/hackdsc/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as HackdscScheduleRouteImport } from './routes/hackdsc/schedule'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HackdscRouteRoute = HackdscRouteRouteImport.update({
  id: '/hackdsc',
  path: '/hackdsc',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRouteRoute = EventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HackdscIndexRoute = HackdscIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HackdscRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRouteRoute,
} as any)
const HackdscScheduleRoute = HackdscScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => HackdscRouteRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteRouteWithChildren
  '/hackdsc': typeof HackdscRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hackdsc/schedule': typeof HackdscScheduleRoute
  '/events/': typeof EventsIndexRoute
  '/hackdsc/': typeof HackdscIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hackdsc/schedule': typeof HackdscScheduleRoute
  '/events': typeof EventsIndexRoute
  '/hackdsc': typeof HackdscIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/hackdsc': typeof HackdscRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hackdsc/schedule': typeof HackdscScheduleRoute
  '/events/': typeof EventsIndexRoute
  '/hackdsc/': typeof HackdscIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/hackdsc'
    | '/about'
    | '/login'
    | '/signup'
    | '/events/$slug'
    | '/hackdsc/schedule'
    | '/events/'
    | '/hackdsc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/events/$slug'
    | '/hackdsc/schedule'
    | '/events'
    | '/hackdsc'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/events'
    | '/hackdsc'
    | '/about'
    | '/_auth/login'
    | '/_auth/signup'
    | '/events/$slug'
    | '/hackdsc/schedule'
    | '/events/'
    | '/hackdsc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  EventsRouteRoute: typeof EventsRouteRouteWithChildren
  HackdscRouteRoute: typeof HackdscRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackdsc': {
      id: '/hackdsc'
      path: '/hackdsc'
      fullPath: '/hackdsc'
      preLoaderRoute: typeof HackdscRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackdsc/': {
      id: '/hackdsc/'
      path: '/'
      fullPath: '/hackdsc/'
      preLoaderRoute: typeof HackdscIndexRouteImport
      parentRoute: typeof HackdscRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/hackdsc/schedule': {
      id: '/hackdsc/schedule'
      path: '/schedule'
      fullPath: '/hackdsc/schedule'
      preLoaderRoute: typeof HackdscScheduleRouteImport
      parentRoute: typeof HackdscRouteRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface EventsRouteRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteRouteChildren: EventsRouteRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteRouteWithChildren = EventsRouteRoute._addFileChildren(
  EventsRouteRouteChildren,
)

interface HackdscRouteRouteChildren {
  HackdscScheduleRoute: typeof HackdscScheduleRoute
  HackdscIndexRoute: typeof HackdscIndexRoute
}

const HackdscRouteRouteChildren: HackdscRouteRouteChildren = {
  HackdscScheduleRoute: HackdscScheduleRoute,
  HackdscIndexRoute: HackdscIndexRoute,
}

const HackdscRouteRouteWithChildren = HackdscRouteRoute._addFileChildren(
  HackdscRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  EventsRouteRoute: EventsRouteRouteWithChildren,
  HackdscRouteRoute: HackdscRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
