/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HackdscRouteRouteImport } from './routes/hackdsc/route'
import { Route as EventsRouteRouteImport } from './routes/events/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HackdscIndexRouteImport } from './routes/hackdsc/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as HackdscScheduleRouteImport } from './routes/hackdsc/schedule'
import { Route as HackdscRegisterRouteImport } from './routes/hackdsc/register'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountOfficerRouteImport } from './routes/account/officer'
import { Route as AccountHackdscRouteImport } from './routes/account/hackdsc'
import { Route as AccountEventsRouteImport } from './routes/account/events'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminHackdscRouteRouteImport } from './routes/admin/hackdsc/route'
import { Route as AdminHackdscIndexRouteImport } from './routes/admin/hackdsc/index'
import { Route as AdminHackdscScheduleRouteImport } from './routes/admin/hackdsc/schedule'
import { Route as AdminHackdscConfigurationRouteImport } from './routes/admin/hackdsc/configuration'
import { Route as AdminHackdscCommunicationsRouteImport } from './routes/admin/hackdsc/communications'
import { Route as AdminHackdscAttendeesRouteImport } from './routes/admin/hackdsc/attendees'
import { Route as AdminHackdscApplicationsRouteImport } from './routes/admin/hackdsc/applications'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HackdscRouteRoute = HackdscRouteRouteImport.update({
  id: '/hackdsc',
  path: '/hackdsc',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRouteRoute = EventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HackdscIndexRoute = HackdscIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HackdscRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const HackdscScheduleRoute = HackdscScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => HackdscRouteRoute,
} as any)
const HackdscRegisterRoute = HackdscRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => HackdscRouteRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountOfficerRoute = AccountOfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountHackdscRoute = AccountHackdscRouteImport.update({
  id: '/hackdsc',
  path: '/hackdsc',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountEventsRoute = AccountEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminHackdscRouteRoute = AdminHackdscRouteRouteImport.update({
  id: '/hackdsc',
  path: '/hackdsc',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHackdscIndexRoute = AdminHackdscIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminHackdscRouteRoute,
} as any)
const AdminHackdscScheduleRoute = AdminHackdscScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminHackdscRouteRoute,
} as any)
const AdminHackdscConfigurationRoute =
  AdminHackdscConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AdminHackdscRouteRoute,
  } as any)
const AdminHackdscCommunicationsRoute =
  AdminHackdscCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AdminHackdscRouteRoute,
  } as any)
const AdminHackdscAttendeesRoute = AdminHackdscAttendeesRouteImport.update({
  id: '/attendees',
  path: '/attendees',
  getParentRoute: () => AdminHackdscRouteRoute,
} as any)
const AdminHackdscApplicationsRoute =
  AdminHackdscApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AdminHackdscRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/hackdsc': typeof HackdscRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/admin/hackdsc': typeof AdminHackdscRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/account/events': typeof AccountEventsRoute
  '/account/hackdsc': typeof AccountHackdscRoute
  '/account/officer': typeof AccountOfficerRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hackdsc/register': typeof HackdscRegisterRoute
  '/hackdsc/schedule': typeof HackdscScheduleRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/hackdsc/': typeof HackdscIndexRoute
  '/admin/hackdsc/applications': typeof AdminHackdscApplicationsRoute
  '/admin/hackdsc/attendees': typeof AdminHackdscAttendeesRoute
  '/admin/hackdsc/communications': typeof AdminHackdscCommunicationsRoute
  '/admin/hackdsc/configuration': typeof AdminHackdscConfigurationRoute
  '/admin/hackdsc/schedule': typeof AdminHackdscScheduleRoute
  '/admin/hackdsc/': typeof AdminHackdscIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/account/events': typeof AccountEventsRoute
  '/account/hackdsc': typeof AccountHackdscRoute
  '/account/officer': typeof AccountOfficerRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hackdsc/register': typeof HackdscRegisterRoute
  '/hackdsc/schedule': typeof HackdscScheduleRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/hackdsc': typeof HackdscIndexRoute
  '/admin/hackdsc/applications': typeof AdminHackdscApplicationsRoute
  '/admin/hackdsc/attendees': typeof AdminHackdscAttendeesRoute
  '/admin/hackdsc/communications': typeof AdminHackdscCommunicationsRoute
  '/admin/hackdsc/configuration': typeof AdminHackdscConfigurationRoute
  '/admin/hackdsc/schedule': typeof AdminHackdscScheduleRoute
  '/admin/hackdsc': typeof AdminHackdscIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/hackdsc': typeof HackdscRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/admin/hackdsc': typeof AdminHackdscRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/account/events': typeof AccountEventsRoute
  '/account/hackdsc': typeof AccountHackdscRoute
  '/account/officer': typeof AccountOfficerRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hackdsc/register': typeof HackdscRegisterRoute
  '/hackdsc/schedule': typeof HackdscScheduleRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/hackdsc/': typeof HackdscIndexRoute
  '/admin/hackdsc/applications': typeof AdminHackdscApplicationsRoute
  '/admin/hackdsc/attendees': typeof AdminHackdscAttendeesRoute
  '/admin/hackdsc/communications': typeof AdminHackdscCommunicationsRoute
  '/admin/hackdsc/configuration': typeof AdminHackdscConfigurationRoute
  '/admin/hackdsc/schedule': typeof AdminHackdscScheduleRoute
  '/admin/hackdsc/': typeof AdminHackdscIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/events'
    | '/hackdsc'
    | '/about'
    | '/join'
    | '/membership'
    | '/privacy'
    | '/admin/hackdsc'
    | '/login'
    | '/signup'
    | '/account/events'
    | '/account/hackdsc'
    | '/account/officer'
    | '/account/settings'
    | '/admin/applications'
    | '/admin/events'
    | '/admin/members'
    | '/admin/settings'
    | '/admin/team'
    | '/auth/callback'
    | '/events/$slug'
    | '/hackdsc/register'
    | '/hackdsc/schedule'
    | '/account/'
    | '/admin/'
    | '/events/'
    | '/hackdsc/'
    | '/admin/hackdsc/applications'
    | '/admin/hackdsc/attendees'
    | '/admin/hackdsc/communications'
    | '/admin/hackdsc/configuration'
    | '/admin/hackdsc/schedule'
    | '/admin/hackdsc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/join'
    | '/membership'
    | '/privacy'
    | '/login'
    | '/signup'
    | '/account/events'
    | '/account/hackdsc'
    | '/account/officer'
    | '/account/settings'
    | '/admin/applications'
    | '/admin/events'
    | '/admin/members'
    | '/admin/settings'
    | '/admin/team'
    | '/auth/callback'
    | '/events/$slug'
    | '/hackdsc/register'
    | '/hackdsc/schedule'
    | '/account'
    | '/admin'
    | '/events'
    | '/hackdsc'
    | '/admin/hackdsc/applications'
    | '/admin/hackdsc/attendees'
    | '/admin/hackdsc/communications'
    | '/admin/hackdsc/configuration'
    | '/admin/hackdsc/schedule'
    | '/admin/hackdsc'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/account'
    | '/admin'
    | '/events'
    | '/hackdsc'
    | '/about'
    | '/join'
    | '/membership'
    | '/privacy'
    | '/admin/hackdsc'
    | '/_auth/login'
    | '/_auth/signup'
    | '/account/events'
    | '/account/hackdsc'
    | '/account/officer'
    | '/account/settings'
    | '/admin/applications'
    | '/admin/events'
    | '/admin/members'
    | '/admin/settings'
    | '/admin/team'
    | '/auth/callback'
    | '/events/$slug'
    | '/hackdsc/register'
    | '/hackdsc/schedule'
    | '/account/'
    | '/admin/'
    | '/events/'
    | '/hackdsc/'
    | '/admin/hackdsc/applications'
    | '/admin/hackdsc/attendees'
    | '/admin/hackdsc/communications'
    | '/admin/hackdsc/configuration'
    | '/admin/hackdsc/schedule'
    | '/admin/hackdsc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EventsRouteRoute: typeof EventsRouteRouteWithChildren
  HackdscRouteRoute: typeof HackdscRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  JoinRoute: typeof JoinRoute
  MembershipRoute: typeof MembershipRoute
  PrivacyRoute: typeof PrivacyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackdsc': {
      id: '/hackdsc'
      path: '/hackdsc'
      fullPath: '/hackdsc'
      preLoaderRoute: typeof HackdscRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackdsc/': {
      id: '/hackdsc/'
      path: '/'
      fullPath: '/hackdsc/'
      preLoaderRoute: typeof HackdscIndexRouteImport
      parentRoute: typeof HackdscRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/hackdsc/schedule': {
      id: '/hackdsc/schedule'
      path: '/schedule'
      fullPath: '/hackdsc/schedule'
      preLoaderRoute: typeof HackdscScheduleRouteImport
      parentRoute: typeof HackdscRouteRoute
    }
    '/hackdsc/register': {
      id: '/hackdsc/register'
      path: '/register'
      fullPath: '/hackdsc/register'
      preLoaderRoute: typeof HackdscRegisterRouteImport
      parentRoute: typeof HackdscRouteRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/officer': {
      id: '/account/officer'
      path: '/officer'
      fullPath: '/account/officer'
      preLoaderRoute: typeof AccountOfficerRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/hackdsc': {
      id: '/account/hackdsc'
      path: '/hackdsc'
      fullPath: '/account/hackdsc'
      preLoaderRoute: typeof AccountHackdscRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/events': {
      id: '/account/events'
      path: '/events'
      fullPath: '/account/events'
      preLoaderRoute: typeof AccountEventsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/hackdsc': {
      id: '/admin/hackdsc'
      path: '/hackdsc'
      fullPath: '/admin/hackdsc'
      preLoaderRoute: typeof AdminHackdscRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hackdsc/': {
      id: '/admin/hackdsc/'
      path: '/'
      fullPath: '/admin/hackdsc/'
      preLoaderRoute: typeof AdminHackdscIndexRouteImport
      parentRoute: typeof AdminHackdscRouteRoute
    }
    '/admin/hackdsc/schedule': {
      id: '/admin/hackdsc/schedule'
      path: '/schedule'
      fullPath: '/admin/hackdsc/schedule'
      preLoaderRoute: typeof AdminHackdscScheduleRouteImport
      parentRoute: typeof AdminHackdscRouteRoute
    }
    '/admin/hackdsc/configuration': {
      id: '/admin/hackdsc/configuration'
      path: '/configuration'
      fullPath: '/admin/hackdsc/configuration'
      preLoaderRoute: typeof AdminHackdscConfigurationRouteImport
      parentRoute: typeof AdminHackdscRouteRoute
    }
    '/admin/hackdsc/communications': {
      id: '/admin/hackdsc/communications'
      path: '/communications'
      fullPath: '/admin/hackdsc/communications'
      preLoaderRoute: typeof AdminHackdscCommunicationsRouteImport
      parentRoute: typeof AdminHackdscRouteRoute
    }
    '/admin/hackdsc/attendees': {
      id: '/admin/hackdsc/attendees'
      path: '/attendees'
      fullPath: '/admin/hackdsc/attendees'
      preLoaderRoute: typeof AdminHackdscAttendeesRouteImport
      parentRoute: typeof AdminHackdscRouteRoute
    }
    '/admin/hackdsc/applications': {
      id: '/admin/hackdsc/applications'
      path: '/applications'
      fullPath: '/admin/hackdsc/applications'
      preLoaderRoute: typeof AdminHackdscApplicationsRouteImport
      parentRoute: typeof AdminHackdscRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AccountRouteRouteChildren {
  AccountEventsRoute: typeof AccountEventsRoute
  AccountHackdscRoute: typeof AccountHackdscRoute
  AccountOfficerRoute: typeof AccountOfficerRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountEventsRoute: AccountEventsRoute,
  AccountHackdscRoute: AccountHackdscRoute,
  AccountOfficerRoute: AccountOfficerRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminHackdscRouteRouteChildren {
  AdminHackdscApplicationsRoute: typeof AdminHackdscApplicationsRoute
  AdminHackdscAttendeesRoute: typeof AdminHackdscAttendeesRoute
  AdminHackdscCommunicationsRoute: typeof AdminHackdscCommunicationsRoute
  AdminHackdscConfigurationRoute: typeof AdminHackdscConfigurationRoute
  AdminHackdscScheduleRoute: typeof AdminHackdscScheduleRoute
  AdminHackdscIndexRoute: typeof AdminHackdscIndexRoute
}

const AdminHackdscRouteRouteChildren: AdminHackdscRouteRouteChildren = {
  AdminHackdscApplicationsRoute: AdminHackdscApplicationsRoute,
  AdminHackdscAttendeesRoute: AdminHackdscAttendeesRoute,
  AdminHackdscCommunicationsRoute: AdminHackdscCommunicationsRoute,
  AdminHackdscConfigurationRoute: AdminHackdscConfigurationRoute,
  AdminHackdscScheduleRoute: AdminHackdscScheduleRoute,
  AdminHackdscIndexRoute: AdminHackdscIndexRoute,
}

const AdminHackdscRouteRouteWithChildren =
  AdminHackdscRouteRoute._addFileChildren(AdminHackdscRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminHackdscRouteRoute: typeof AdminHackdscRouteRouteWithChildren
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminHackdscRouteRoute: AdminHackdscRouteRouteWithChildren,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface EventsRouteRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteRouteChildren: EventsRouteRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteRouteWithChildren = EventsRouteRoute._addFileChildren(
  EventsRouteRouteChildren,
)

interface HackdscRouteRouteChildren {
  HackdscRegisterRoute: typeof HackdscRegisterRoute
  HackdscScheduleRoute: typeof HackdscScheduleRoute
  HackdscIndexRoute: typeof HackdscIndexRoute
}

const HackdscRouteRouteChildren: HackdscRouteRouteChildren = {
  HackdscRegisterRoute: HackdscRegisterRoute,
  HackdscScheduleRoute: HackdscScheduleRoute,
  HackdscIndexRoute: HackdscIndexRoute,
}

const HackdscRouteRouteWithChildren = HackdscRouteRoute._addFileChildren(
  HackdscRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EventsRouteRoute: EventsRouteRouteWithChildren,
  HackdscRouteRoute: HackdscRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  JoinRoute: JoinRoute,
  MembershipRoute: MembershipRoute,
  PrivacyRoute: PrivacyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
